### ISSUE TITLE
Access packet source and destination addresses

### ISSUE THREAD

**Issue by Camotubi** [courvoif/pcap-file#6]
Hi,
First of all thanks for your work. This library has been very helpful. I would want to know if it is possible to read the IP addresses. I have been reading the docs, but I'm not able to find a way to get it.

**Comment by courvoif** [comment]
Hello,
I'm glad that you found my library helpful :)
It's not possible to read the IPs because this lib doesn't parse the content of the packets. Its only purpose is to read/write packets saved in the pcap format.
The only metadata stored in a pcap file are the timestamp and the size of the packets.

If you want to extract the IP addresses of the packets you'll have to read your pcap with pcap-file and then parse the content of the packets by hand or use a library to do that. You could use something like [etherparse](https://github.com/JulianSchmid/etherparse) or [peel-ip](https://github.com/saschagrunert/peel-ip) I think. I never tried them but they seem to be what you're looking for.

**Comment by Camotubi** [comment]
Oh ok ok. I was wondering why IP wasn't mentioned anywhere. 
Ill look into etherparse. Thank you for pointing me into the right direction.
